### ISSUE TITLE
Cadastro - "404 Not Found"

### ISSUE THREAD

**Issue by aylasantos** [redebloomie/bloomie-website#1]
Ao testar o "cadastro.html", o preenchimento do formulário redireciona à uma página de "404 Not Found" - "The requested URL was not found on this server." O caminho das pastas mencionadas no código está indexado corretamente. O problema, entretanto, persiste. 

![image](https://github.com/redebloomie/bloomie-website/assets/91627125/efd46a0f-dcb0-47c9-bc8a-9f2698cf8d21)

**Comment by winnie-s3** [comment]
Resolvido.
